name: unit_test
description: This repository is an example that will be used in the Unit Test Medium article.
version: 1.0.0
repository: https://github.com/JotaPe-Tecnologia/medium/tree/main/unit_test
homepage: https://www.jotapetecnologia.com.br/flutter/packages/articles/unit-test

environment:
  sdk: ^3.2.6

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
