name: unit_test
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/JotaPe-Tecnologia/medium
homepage: https://www.jotapetecnologia.com.br/flutter/packages/medium

environment:
  sdk: ^3.2.6

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
